### PR TITLE
Dump database again

### PR DESCRIPTION
**Pull request by emanuelen5**

### CODE REVIEW

**Comment by emanuelen5** [comment]
Have not been able to make diff work with pickle dumps... Error message: `*** TypeError: unhashable type: 'pyodbc.Row'`

**Comment by emanuelen5** [comment]
Ska vi kanske ta bort merge:ade brancher?

**Comment by roos-work** [comment]
Absolut, det kan vi göra.

**Comment by roos-work** [comment]
Tog bort de omergade nu.

**Pull request merged**
